const products = [
    {
        "_id": "1",
        name: "RECTANGLE PEACOAT IN WOOL NAVY",
        image: "/images/image-4.jpeg",
        description: "90% WOOL 10% POLYAMIDE - MIDDLE BACK VENT - 6 CELINE-ENGRAVED HORN BUTTONS - CLASSIC FIT",
        brand: "CELINE",
        category: "Men's Winter Wear",
        price: "2,450",
        countInStock: "10",
        availableSizes: ["XS", "S", "M", "L"],
        rating: 3.0,
        numReviews: 3,
    },
    {
        "_id": "2",
        name: "RECTANGLE PEACOAT IN WOOL NAVY",
        image: "/images/image-4.jpeg",
        description: "90% WOOL 10% POLYAMIDE - MIDDLE BACK VENT - 6 CELINE-ENGRAVED HORN BUTTONS - CLASSIC FIT",
        brand: "CELINE",
        category: "Men's Winter Wear",
        price: "2,450",
        countInStock: "0",
        availableSizes: ["XS", "S", "M", "L"],
        rating: 4.0,
        numReviews: 12,
    },
    {
        "_id": "3",
        name: "RECTANGLE PEACOAT IN WOOL NAVY",
        image: "/images/image-4.jpeg",
        description: "90% WOOL 10% POLYAMIDE - MIDDLE BACK VENT - 6 CELINE-ENGRAVED HORN BUTTONS - CLASSIC FIT",
        brand: "CELINE",
        category: "Men's Winter Wear",
        price: "2,450",
        countInStock: "5",
        availableSizes: ["XS", "S", "M", "L"],
        rating: 5.0,
        numReviews: 10,
    },
    {
        "_id": "4",
        name: "RECTANGLE PEACOAT IN WOOL NAVY",
        image: "/images/image-4.jpeg",
        description: "90% WOOL 10% POLYAMIDE - MIDDLE BACK VENT - 6 CELINE-ENGRAVED HORN BUTTONS - CLASSIC FIT",
        brand: "CELINE",
        category: "Men's Winter Wear",
        price: "2,450",
        countInStock: "5",
        availableSizes: ["XS", "S", "M", "L"],
        rating: 3.0,
        numReviews: 9,
    },
    {
        "_id": "5",
        name: "RECTANGLE PEACOAT IN WOOL NAVY",
        image: "/images/image-4.jpeg",
        description: "90% WOOL 10% POLYAMIDE - MIDDLE BACK VENT - 6 CELINE-ENGRAVED HORN BUTTONS - CLASSIC FIT",
        brand: "CELINE",
        category: "Men's Winter Wear",
        price: "2,450",
        countInStock: "5",
        availableSizes: ["XS", "S", "M", "L"],
        rating: 3.5,
        numReviews: 3,
    },
    {
        "_id": "6",
        name: "RECTANGLE PEACOAT IN WOOL NAVY",
        image: "/images/image-4.jpeg",
        description: "90% WOOL 10% POLYAMIDE - MIDDLE BACK VENT - 6 CELINE-ENGRAVED HORN BUTTONS - CLASSIC FIT",
        brand: "CELINE",
        category: "Men's Winter Wear",
        price: "2,450",
        countInStock: "5",
        availableSizes: ["XS", "S", "M", "L"],
        rating: 4.0,
        numReviews: 7,
    },
    {
        "_id": "7",
        name: "RECTANGLE PEACOAT IN WOOL NAVY",
        image: "/images/image-4.jpeg",
        description: "90% WOOL 10% POLYAMIDE - MIDDLE BACK VENT - 6 CELINE-ENGRAVED HORN BUTTONS - CLASSIC FIT",
        brand: "CELINE",
        category: "Men's Winter Wear",
        price: "2,450",
        countInStock: "5",
        availableSizes: ["XS", "S", "M", "L"],
        rating: 5.0,
        numReviews: 11,
    },
    {
        "_id": "8",
        name: "RECTANGLE PEACOAT IN WOOL NAVY",
        image: "/images/image-4.jpeg",
        description: "90% WOOL 10% POLYAMIDE - MIDDLE BACK VENT - 6 CELINE-ENGRAVED HORN BUTTONS - CLASSIC FIT",
        brand: "CELINE",
        category: "Men's Winter Wear",
        price: "2,450",
        countInStock: "5",
        availableSizes: ["XS", "S", "M", "L"],
        rating: 2.0,
        numReviews: 16,
    },
]

export default products